Robot to Node April Tag angle calculation added
Tino-FRC-2473/FRC2023 pull request #53
Opened 2023-02-04 23:26 UTC by MG-05

2023-02-07 07:48 UTC, AG6GR requested changes
Just FYI, "align" has one L.

2023-02-07 07:48 UTC, AG6GR commented on src/main/java/frc/robot/Constants.java
> +	public static final double METERS_TO_INCHES_CONSTANT = 39.3701;
Use Units.metersToInches

2023-02-07 07:48 UTC, AG6GR commented on src/main/java/frc/robot/TeleopInput.java
> +	private static final int CV_ALLIGN_BUTTON_LEFT_NODE = 4;
Spelling. Also please add to the teleop button map spreadsheet.

2023-02-07 07:48 UTC, AG6GR commented on src/main/java/frc/robot/systems/DriveFSMSystem.java
> +				xToATag = pcw.getEstimatedGlobalPose().get().estimatedPose.getX()
Move these into the handleCVAllignState function.

2023-02-07 07:48 UTC, AG6GR commented on src/main/java/frc/robot/systems/DriveFSMSystem.java
> +				angleToTurnToFaceTag = -1 * (Constants.ONE_REVOLUTION_DEGREES - Math.toDegrees(
These couple lines would be a lot more readable if you stored `pcw.getEstimatedGlobalPose().get().estimatedPose` to a function local variable.

2023-02-07 07:48 UTC, AG6GR commented on src/main/java/frc/robot/systems/DriveFSMSystem.java
> +				if (pcw.getEstimatedGlobalPose().get().estimatedPose.getY() < 0) {
Is this just doing absolute value? I think if you simplify the math you don't need the if else.

2023-02-09 06:23 UTC, AG6GR commented on src/main/java/frc/robot/systems/DriveFSMSystem.java
> +				pcw.getEstimatedGlobalPose().get().estimatedPose.getX()
I meant we shouldn't need METERS_TO_INCHES_CONSTANT, just call the conversion function instead.

2023-02-09 06:51 UTC, AG6GR approved these changes

2023-02-10 20:29 UTC, mirapanigrahy approved these changes

2023-02-10 23:42 UTC, merged