CV drive FSM integration
Tino-FRC-2473/FRC2023 pull request #63
Opened 2023-02-21 07:48 UTC by AknA13

Added CV align and drive-up states with the drive FSMs. This allows CV-guided drive to be run during teleop.

2023-02-22 04:07 UTC, AG6GR requested changes

2023-02-22 04:07 UTC, AG6GR commented on src/main/java/frc/robot/Constants.java
> +	// Path points
What are the units here? Also I really feel like these points should be [Translation2D](https://github.wpilib.org/allwpilib/docs/release/java/edu/wpi/first/math/geometry/Translation2d.html) objects

2023-02-22 04:07 UTC, AG6GR commented on src/main/java/frc/robot/Constants.java
> +		static final double CAM_OFFSET_Y_METERS = Units.inchesToMeters(8.6);
If we already have a VisionConstants subsection, can we put the rest of the CV related constants under here as well for organization?

2023-02-22 04:07 UTC, AG6GR commented on src/main/java/frc/robot/HardwareMap.java
> +	// public static final int CAN_ID_SPARK_DRIVE_LEFT1 = 31;
Please rebase for the latest SPARK Max ID assignments.

2023-02-22 04:07 UTC, AG6GR commented on src/main/java/frc/robot/systems/ArmFSM.java
> +	private static final double PID_MAX_POWER = 0.3;
Please reset the FSM you didn't modify to the version on main.

2023-02-22 04:07 UTC, AG6GR commented on src/main/java/frc/robot/systems/DriveFSMSystem.java
> +		CVLowTapeAlign,
Constants should be all caps.

2023-02-22 04:07 UTC, AG6GR commented on src/main/java/frc/robot/systems/DriveFSMSystem.java
> +	// private CANSparkMax leftMotor1;
Clean up unused code

2023-02-22 04:07 UTC, AG6GR commented on src/main/java/frc/robot/systems/DriveFSMSystem.java
> +	private boolean forward = false;
Please use a more descriptive name. Also booleans should all be named starting with "is" i.e. "isXYZ"

2023-02-22 04:07 UTC, AG6GR commented on src/main/java/frc/robot/systems/DriveFSMSystem.java
> +		// leftMotor1 = new CANSparkMax(HardwareMap.CAN_ID_SPARK_DRIVE_LEFT1,
Remove unused code.

2023-02-22 04:07 UTC, AG6GR commented on src/main/java/frc/robot/systems/DriveFSMSystem.java
> +			// if (!pcw.getEstimatedGlobalPose().isEmpty()) {
Remove unused code

2023-02-22 20:31 UTC, AknA13 commented on src/main/java/frc/robot/Constants.java
> +	// Path points
That's up to drive on whether they want to use Translation2d or represent their points as these.

2023-02-23 01:03 UTC, SamNat975 commented on src/main/java/frc/robot/Constants.java
> +	// Path points
Drive said they preferred their points like this so we're just leaving them like that.

2023-02-23 02:32 UTC, SamNat975 commented
i rebased off of main and i had to squash all the commits on this into one commit— and then mavis told me to force-push the dummy branch onto this pull request
the code still needs to be fixed because it has errors in teleop though

2023-02-25 18:26 UTC, SamNat975 commented
addressed merge conflict errors

2023-02-25 19:10 UTC, AG6GR approved these changes

2023-02-25 19:17 UTC, merged